INSERT INTO CAT_PERMISSION_SEGMENT (CODE, DESCRIPTION, `ORDER`) VALUES
("SECURITY_MANAGEMENT", 'Gestión de seguridad', 9);

INSERT INTO CAT_PERMISSION(CODE,DESCRIPTION,APPLIES_TO_USER_TYPE,CREATION_DATE,ENABLED,`ORDER`,SEGMENT_CODE) VALUES 
("READ_ROLE_LIST", "Ver listado de roles", "LIBERA_USER", CURRENT_TIMESTAMP, 1, 1, "SECURITY_MANAGEMENT"),
("CREATE_ROLE", "Crear rol", "LIBERA_USER", CURRENT_TIMESTAMP, 1, 2, "SECURITY_MANAGEMENT"),
("UPDATE_ROLE", "Editar rol", "LIBERA_USER", CURRENT_TIMESTAMP, 1, 3, "SECURITY_MANAGEMENT"),
("ENABLE_OR_DISABLE_ROLE", "Habilitar/Deshabilitar", "LIBERA_USER", CURRENT_TIMESTAMP, 1, 4, "SECURITY_MANAGEMENT");