INSERT INTO CODES_CIIU (CIIU, ACTIVIDAD_ECONOMICA, SECTOR_ECONOMICO) VALUES
('0111', 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0112', 'Cultivo de arroz', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0113', 'Cultivo de hortalizas, raíces y tubérculos', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0114', 'Cultivo de tabaco', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0115', 'Cultivo de plantas textiles', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0119', 'Otros cultivos transitorios n.c.p.', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0121', 'Cultivo de frutas tropicales y subtropicales', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0122', 'Cultivo de plátano y banano', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0123', 'Cultivo de café', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0124', 'Cultivo de caña de azúcar', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0125', 'Cultivo de flor de corte', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0126', 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0127', 'Cultivo de plantas con las que se prepararan bebidas', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0128', 'Cultivo de especias y de plantas aromáticas y medicinales', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0129', 'Otros cultivos permanentes n.c.p.', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0130', 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0141', 'Cría de ganado bovino y bufalino', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0142', 'Cría de caballos y otros equinos', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0143', 'Cría de ovejas y cabras', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0144', 'Cría de ganado porcino', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0145', 'Cría de aves de corral', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0149', 'Cría de otros animales n.c.p.', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0150', 'Explotación mixta (agrícola y pecuaria)', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0161', 'Actividades de apoyo a la agricultura', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0162', 'Actividades de apoyo a la ganadería', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0163', 'Actividades posteriores a la cosecha', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0164', 'Tratamiento de semillas para propagación', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0170', 'Caza ordinaria y mediante trampas y actividades de servicios conexas', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0210', 'Silvicultura y otras actividades forestales', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0220', 'Extracción de madera', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0230', 'Recolección de productos forestales diferentes a la madera', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0240', 'Servicios de apoyo a la silvicultura', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0311', 'Pesca marítima', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0312', 'Pesca de agua dulce', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0321', 'Acuicultura marítima', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0322', 'Acuicultura de agua dulce', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA (DIVISIÓN 1,2 Y 3)'),
('0510', 'Extracción de hulla (carbón de piedra)', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0520', 'Extracción de carbón lignito', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0610', 'Extracción de petróleo crudo', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0620', 'Extracción de gas natural', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0710', 'Extracción de minerales de hierro', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0721', 'Extracción de minerales de uranio y de torio', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0722', 'Extracción de oro y otros metales preciosos', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0723', 'Extracción de minerales de níquel', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0729', 'Extracción de otros minerales metalíferos no ferrosos n.c.p.', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0811', 'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0812', 'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0820', 'Extracción de esmeraldas, piedras preciosas y semipreciosas', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0891', 'Extracción de minerales para la fabricación de abonos y productos químicos', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0892', 'Extracción de halita (sal)', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0899', 'Extracción de otros minerales no metálicos n.c.p.', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0910', 'Actividades de apoyo para la extracción de petróleo y de gas natural', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('0990', 'Actividades de apoyo para otras actividades de explotación de minas y canteras', 'EXPLOTACIÓN DE MINAS Y CANTERAS (DIVISIÓN  5, 6, 7, 8 Y 9)'),
('1011', 'Procesamiento y conservación de carne y productos cárnicos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1012', 'Procesamiento y conservación de pescados, crustáceos y moluscos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1020', 'Procesamiento y conservación de frutas, legumbres, hortalizas y tuberculos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1030', 'Elaboración de aceites y grasas de origen vegetal y animal', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1040', 'Elaboración de productos lácteos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1051', 'Elaboración de productos de molinería', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1052', 'Elaboración de almidones y productos derivados del almidón', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1061', 'Trilla de café', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1062', 'Descafeinado, tostión y molienda del café', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1063', 'Otros derivados del café', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1071', 'Elaboración y refinación de azúcar', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1072', 'Elaboración de panela', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1081', 'Elaboración de productos de panadería', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1082', 'Elaboración de cacao, chocolate y productos de confitería', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1083', 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1084', 'Elaboración de comidas y platos preparados', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1089', 'Elaboración de otros productos alimenticios n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1090', 'Elaboración de alimentos preparados para animales', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1101', 'Destilación, rectificación y mezcla de bebidas alcohólicas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1102', 'Elaboración de bebidas fermentadas no destiladas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1103', 'Producción de malta, elaboración de cervezas y otras bebidas malteadas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1104', 'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1200', 'Elaboración de productos de tabaco', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1311', 'Preparación e hilatura de fibras textiles', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1312', 'Tejeduría de productos textiles', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1313', 'Acabado de productos textiles', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1391', 'Fabricación de tejidos de punto y ganchillo', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1392', 'Confección de artículos con materiales textiles, excepto prendas de vestir', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1393', 'Fabricación de tapetes y alfombras para pisos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1394', 'Fabricación de cuerdas, cordeles, cables, bramantes y redes', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1399', 'Fabricación de otros artículos textiles n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1410', 'Confección de prendas de vestir, excepto prendas de piel', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1420', 'Fabricación de artículos de piel', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1430', 'Fabricación de artículos de punto y ganchillo', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1511', 'Curtido y recurtido de cueros  recurtido y teñido de pieles.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1512', 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1513', 'Fabricación de artículos de viaje, bolsos de mano y artículos similares  artículos de talabartería y guarnicionería elaborados en otros materiales', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1521', 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1522', 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1523', 'Fabricación de partes del calzado', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1610', 'Aserrado, acepillado e impregnación de la madera', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1620', 'Fabricación de hojas de madera para enchapado  fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1630', 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1640', 'Fabricación de recipientes de madera', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1690', 'Fabricación de otros productos de madera  fabricación de artículos de corcho, cestería y espartería', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1701', 'Fabricación de pulpas (pastas) celulósicas  papel y cartón', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1702', 'Fabricación de papel y cartón ondulado (corrugado)  fabricación de envases, empaques y de embalajes de papel y cartón.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1709', 'Fabricación de otros artículos de papel y cartón', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1811', 'Actividades de impresión', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1812', 'Actividades de servicios relacionados con la impresión', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1820', 'Producción de copias a partir de grabaciones originales', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1910', 'Fabricación de productos de hornos de coque', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1921', 'Fabricación de productos de la refinación del petróleo', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('1922', 'Actividad de mezcla de combustibles', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2011', 'Fabricación de sustancias y productos químicos básicos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2012', 'Fabricación de abonos y compuestos inorgánicos nitrogenados', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2013', 'Fabricación de plásticos en formas primarias', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2014', 'Fabricación de caucho sintético en formas primarias', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2021', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2022', 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2023', 'Fabricación de jabones y detergentes, preparados para limpiar y pulir  perfumes y preparados de tocador', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2029', 'Fabricación de otros productos químicos n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2030', 'Fabricación de fibras sintéticas y artificiales', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2100', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2211', 'Fabricación de llantas y neumáticos de caucho', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2212', 'Reencauche de llantas usadas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2219', 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2221', 'Fabricación de formas básicas de plástico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2229', 'Fabricación de artículos de plástico n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2310', 'Fabricación de vidrio y productos de vidrio', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2391', 'Fabricación de productos refractarios', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2392', 'Fabricación de materiales de arcilla para la construcción', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2393', 'Fabricación de otros productos de cerámica y porcelana', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2394', 'Fabricación de cemento, cal y yeso', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2395', 'Fabricación de artículos de hormigón, cemento y yeso', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2396', 'Corte, tallado y acabado de la piedra', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2399', 'Fabricación de otros productos minerales no metálicos n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2410', 'Industrias básicas de hierro y de acero', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2421', 'Industrias básicas de metales preciosos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2429', 'Industrias básicas de otros metales no ferrosos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2431', 'Fundición de hierro y de acero', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2432', 'Fundición de metales no ferrosos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2511', 'Fabricación de productos metálicos para uso estructural', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2512', 'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2513', 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2520', 'Fabricación de armas y municiones', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2591', 'Forja, prensado, estampado y laminado de metal  pulvimetalurgia', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2592', 'Tratamiento y revestimiento de metales  mecanizado', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2593', 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2599', 'Fabricación de otros productos elaborados de metal n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2610', 'Fabricación de componentes y tableros electrónicos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2620', 'Fabricación de computadoras y de equipo periférico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2630', 'Fabricación de equipos de comunicación', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2640', 'Fabricación de aparatos electrónicos de consumo', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2651', 'Fabricación de equipo de medición, prueba, navegación y control', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2652', 'Fabricación de relojes', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2660', 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2670', 'Fabricación de instrumentos ópticos y equipo fotográfico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2680', 'Fabricación de soportes magnéticos y ópticos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2711', 'Fabricación de motores, generadores y transformadores eléctricos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2712', 'Fabricación de aparatos de distribución y control de la energía eléctrica', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2720', 'Fabricación de pilas, baterías y acumuladores eléctricos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2731', 'Fabricación de hilos y cables eléctricos y de fibra óptica', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2732', 'Fabricación de dispositivos de cableado', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2740', 'Fabricación de equipos eléctricos de iluminación', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2750', 'Fabricación de aparatos de uso doméstico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2790', 'Fabricación de otros tipos de equipo eléctrico n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2811', 'Fabricación de motores, turbinas, y partes para motores de combustión interna', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2812', 'Fabricación de equipos de potencia hidráulica y neumática', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2813', 'Fabricación de otras bombas, compresores, grifos y válvulas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2814', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2815', 'Fabricación de hornos, hogares y quemadores industriales', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2816', 'Fabricación de equipo de elevación y manipulación', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2817', 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2818', 'Fabricación de herramientas manuales con motor', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2819', 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p..', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2821', 'Fabricación de maquinaria agropecuaria y forestal', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2822', 'Fabricación de máquinas formadoras de metal y de máquinas herramienta', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2823', 'Fabricación de maquinaria para la metalurgia', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2824', 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2825', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2826', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2829', 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2910', 'Fabricación de vehículos automotores y sus motores', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2920', 'Fabricación de carrocerías para vehículos automotores  fabricación de remolques y semirremolques', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('2930', 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3011', 'Construcción de barcos y de estructuras flotantes', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3012', 'Construcción de embarcaciones de recreo y deporte', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3020', 'Fabricación de locomotoras y de material rodante para ferrocarriles', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3030', 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3040', 'Fabricación de vehículos militares de combate', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3091', 'Fabricación de motocicletas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3092', 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3099', 'Fabricación de otros tipos de equipo de transporte n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3110', 'Fabricación de muebles', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3120', 'Fabricación de colchones y somieres', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3210', 'Fabricación de joyas, bisutería y artículos conexos', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3220', 'Fabricación de instrumentos musicales', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3230', 'Fabricación de artículos y equipo para la práctica del deporte', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3240', 'Fabricación de juegos, juguetes y rompecabezas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3250', 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3290', 'Otras industrias manufactureras n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3311', 'Mantenimiento y reparación especializado de productos elaborados en metal', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3312', 'Mantenimiento y reparación especializado de maquinaria y equipo', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3313', 'Mantenimiento y reparación especializado de equipo electrónico y óptico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3314', 'Mantenimiento y reparación especializado de equipo eléctrico', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3315', 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3319', 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3320', 'Instalación especializada de maquinaria y equipo industrial', 'INDUSTRIAS MANUFACTURERAS (DIVISIÓN 10 AL 33)'),
('3511', 'Generación de energía eléctrica', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO (DIVISIÓN 35)'),
('3512', 'Transmisión de energía eléctrica', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO (DIVISIÓN 35)'),
('3513', 'Distribución de energía eléctrica', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO (DIVISIÓN 35)'),
('3514', 'Comercialización de energía eléctrica', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO (DIVISIÓN 35)'),
('3520', 'Producción de gas  distribución de combustibles gaseosos por tuberías', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO (DIVISIÓN 35)'),
('3530', 'Suministro de vapor y aire acondicionado', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO (DIVISIÓN 35)'),
('3600', 'Captación, tratamiento y distribución de agua', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('3700', 'Evacuación y tratamiento de aguas residuales', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('3811', 'Recolección de desechos no peligrosos', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('3812', 'Recolección de desechos peligrosos', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('3821', 'Tratamiento y disposición de desechos no peligrosos', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('3822', 'Tratamiento y disposición de desechos peligrosos', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('3830', 'Recuperación de materiales', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('3900', 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos', 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN (DIVISIÓN 36, 37, 38 Y 39)'),
('4111', 'Construcción de edificios residenciales', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4112', 'Construcción de edificios no residenciales', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4210', 'Construcción de carreteras y vías de ferrocarril', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4220', 'Construcción de proyectos de servicio público', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4290', 'Construcción de otras obras de ingeniería civil', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4311', 'Demolición', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4312', 'Preparación del terreno', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4321', 'Instalaciones eléctricas', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4322', 'Instalaciones de fontanería, calefacción y aire acondicionado', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4329', 'Otras instalaciones especializadas', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4330', 'Terminación y acabado de edificios y obras de ingeniería civil', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4390', 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil', 'CONSTRUCCIÓN (DIVISIÓN 41, 42, 43)'),
('4511', 'Comercio de vehículos automotores nuevos', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4512', 'Comercio de vehículos automotores usados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4520', 'Mantenimiento y reparación de vehículos automotores', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4530', 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4541', 'Comercio de motocicletas y de sus partes, piezas y accesorios', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4542', 'Mantenimiento y reparación de motocicletas y de sus partes y piezas', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4610', 'Comercio al por mayor a cambio de una retribución o por contrata', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4620', 'Comercio al por mayor de materias primas agropecuarias  animales vivos', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4631', 'Comercio al por mayor de productos alimenticios', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4632', 'Comercio al por mayor de bebidas y tabaco', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4641', 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4642', 'Comercio al por mayor de prendas de vestir', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4643', 'Comercio al por mayor de calzado', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4644', 'Comercio al por mayor de aparatos y equipo de uso doméstico', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4645', 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4649', 'Comercio al por mayor de otros utensilios domésticos n.c.p.', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4651', 'Comercio al por mayor de computadores, equipo periférico y programas de informática', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4652', 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4653', 'Comercio al por mayor de maquinaria y equipo agropecuarios', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4659', 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4661', 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4662', 'Comercio al por mayor de metales y productos metalíferos', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4663', 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4664', 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4665', 'Comercio al por mayor de desperdicios, desechos y chatarra', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4669', 'Comercio al por mayor de otros productos n.c.p.', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4690', 'Comercio al por mayor no especializado', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4711', 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4719', 'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4721', 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4722', 'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4723', 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4724', 'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4729', 'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4731', 'Comercio al por menor de combustible para automotores', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4732', 'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4741', 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4742', 'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4751', 'Comercio al por menor de productos textiles en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4752', 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4753', 'Comercio al por menor de tapices, alfombras y recubrimientos para paredes y pisos en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4754', 'Comercio al por menor de electrodomésticos y gasodomesticos de uso doméstico, muebles y equipos de iluminación', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4755', 'Comercio al por menor de artículos y utensilios de uso doméstico', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4759', 'Comercio al por menor de otros artículos domésticos en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4761', 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4762', 'Comercio al por menor de artículos deportivos, en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4769', 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4771', 'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4772', 'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4773', 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4774', 'Comercio al por menor de otros productos nuevos en establecimientos especializados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4775', 'Comercio al por menor de artículos de segunda mano', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4781', 'Comercio al por menor de alimentos, bebidas y tabaco en puestos de venta móviles', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4782', 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4789', 'Comercio al por menor de otros productos en puestos de venta móviles', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4791', 'Comercio al por menor realizado a través de Internet', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4792', 'Comercio al por menor realizado a través de casas de venta o por correo', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4799', 'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados', 'COMERCIO AL POR MAYOR Y AL POR MENOR, REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS (DIVISIÓN 45, 46 Y 47)'),
('4911', 'Transporte férreo de pasajeros', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('4912', 'Transporte férreo de carga', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('4921', 'Transporte de pasajeros', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('4922', 'Transporte mixto', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('4923', 'Transporte de carga por carretera', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('4930', 'Transporte por tuberías', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5011', 'Transporte de pasajeros marítimo y de cabotaje', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5012', 'Transporte de carga marítimo y de cabotaje', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5021', 'Transporte fluvial de pasajeros', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5022', 'Transporte fluvial de carga', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5111', 'Transporte aéreo nacional de pasajeros', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5112', 'Transporte aéreo internacional de pasajeros', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5121', 'Transporte aéreo nacional de carga', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5122', 'Transporte aéreo internacional de carga', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5210', 'Almacenamiento y depósito', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5221', 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5222', 'Actividades de puertos y servicios complementarios para el transporte acuático', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5223', 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5224', 'Manipulación de carga', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5229', 'Otras actividades complementarias al transporte', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5310', 'Actividades postales nacionales', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5320', 'Actividades de mensajería', 'TRANSPORTE Y ALMACENAMIENTO (DIVISIÓN 49, 50, 51, 52 Y 53)'),
('5511', 'Alojamiento en hoteles', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5512', 'Alojamiento en aparta-hoteles', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5513', 'Alojamiento en centros vacacionales', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5514', 'Alojamiento rural', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5519', 'Otros tipos de alojamientos para visitantes', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5520', 'Actividades de zonas de camping y parques para vehículos recreacionales', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5530', 'Servicio por horas', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5590', 'Otros tipos de alojamiento n.c.p.', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5611', 'Expendio a la mesa de comidas preparadas', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5612', 'Expendio por autoservicio de comidas preparadas', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5613', 'Expendio de comidas preparadas en cafeterías', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5619', 'Otros tipos de expendio de comidas preparadas n.c.p.', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5621', 'Catering para eventos', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5629', 'Actividades de otros servicios de comidas', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5630', 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS (DIVISIÓN 55 Y 56)'),
('5811', 'Edición de libros', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5812', 'Edición de directorios y listas de correo', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5813', 'Edición de periódicos, revistas y otras publicaciones periódicas', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5819', 'Otros trabajos de edición', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5820', 'Edición de programas de informática (software)', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5911', 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5912', 'Actividades de postproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5913', 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5914', 'Actividades de exhibición de películas cinematográficas y videos', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('5920', 'Actividades de grabación de sonido y edición de musica', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6010', 'Actividades de programación y transmisión en el servicio de radiodifusión sonora', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6020', 'Actividades de programación y transmisión de televisión', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6110', 'Actividades de telecomunicaciones alámbricas', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6120', 'Actividades de telecomunicaciones inalámbricas', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6130', 'Actividades de telecomunicación satelital', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6190', 'Otras actividades de telecomunicaciones', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6201', 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6202', 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6209', 'Otras actividades de tecnologías de información y actividades de servicios informáticos', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6311', 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6312', 'Portales Web', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6391', 'Actividades de agencias de noticias', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6399', 'Otras actividades de servicio de información n.c.p.', 'INFORMACIÓN Y COMUNICACIONES (DIVISIÓN 58, AL 63)'),
('6411', 'Banco Central', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6412', 'Bancos comerciales', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6421', 'Actividades de las corporaciones financieras', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6422', 'Actividades de las compañías de financiamiento', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6423', 'Banca de segundo piso', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6424', 'Actividades de las cooperativas financieras', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6431', 'Fideicomisos, fondos y entidades financieras similares', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6432', 'Fondos de cesantías', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6491', 'Leasing financiero (arrendamiento financiero)', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6492', 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6493', 'Actividades de compra de cartera o factoring', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6494', 'Otras actividades de distribución de fondos', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6495', 'Instituciones especiales oficiales', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6499', 'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6511', 'Seguros generales', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6512', 'Seguros de vida', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6513', 'Reaseguros', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6514', 'Capitalización', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6521', 'Servicios de seguros sociales de salud', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6522', 'Servicios de seguros sociales de riesgos profesionales', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6531', 'Régimen de prima media con prestación definida (RPM)', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6532', 'Régimen de ahorro individual (RAI).', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6611', 'Administración de mercados financieros', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6612', 'Corretaje de valores y de contratos de productos básicos', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6613', 'Otras actividades relacionadas con el mercado de valores', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6614', 'Actividades de las casas de cambio', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6615', 'Actividades de los profesionales de compra y venta de divisas', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6619', 'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6621', 'Actividades de agentes y corredores de seguros', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6629', 'Evaluación de riesgos y daños y otras actividades de servicios auxiliares', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6630', 'Actividades de administración de fondos', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS (DIVISIÓN 64, 65 Y 66) PRUEBA'),
('6810', 'Actividades inmobiliarias realizadas con bienes propios o arrendados', 'ACTIVIDADES INMOBILIARIAS (DIVISIÓN 68)'),
('6820', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata', 'ACTIVIDADES INMOBILIARIAS (DIVISIÓN 68)'),
('6910', 'Actividades jurídicas', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('6920', 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7010', 'Actividades de administración empresarial', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7020', 'Actividades de consultaría de gestión', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7110', 'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7120', 'Ensayos y análisis técnicos', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7210', 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7220', 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7310', 'Publicidad', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7320', 'Estudios de mercado y realización de encuestas de opinión pública', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7410', 'Actividades especializadas de diseño', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7420', 'Actividades de fotografía', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7490', 'Otras actividades profesionales, científicas y técnicas n.c.p.', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7500', 'Actividades veterinarias', 'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS (DIVISIÓN 69 AL 75)'),
('7710', 'Alquiler y arrendamiento de vehículos automotores', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7721', 'Alquiler y arrendamiento de equipo recreativo y deportivo', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7722', 'Alquiler de videos y discos', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7729', 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7730', 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7740', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7810', 'Actividades de agencias de empleo', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7820', 'Actividades de agencias de empleo temporal', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7830', 'Otras actividades de suministro de recurso humano', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7911', 'Actividades de las agencias de viajes', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7912', 'Actividades de operadores turísticos', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('7990', 'Otros servicios de reserva y actividades relacionadas', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8010', 'Actividades de seguridad privada', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8020', 'Actividades de servicios de sistemas de seguridad', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8030', 'Actividades de detectives e investigadores privados', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8110', 'Actividades combinadas de apoyo a instalaciones', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8121', 'Limpieza general interior de edificios', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8129', 'Otras actividades de limpieza de edificios e instalaciones industriales', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8130', 'Actividades de paisajismo y servicios de mantenimiento conexos', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8211', 'Actividades combinadas de servicios administrativos de oficina', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8219', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8220', 'Actividades de centros de llamadas (Call center)', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8230', 'Organización de convenciones y eventos comerciales', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8291', 'Actividades de agencias de cobranza y oficinas de calificación crediticia', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8292', 'Actividades de envase y empaque', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8299', 'Otras actividades de servicio de apoyo a las empresas n.c.p.', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO (DIVISIÓN 77 AL 82)'),
('8411', 'Actividades legislativas de la administración pública', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8412', 'Actividades ejecutivas de la administración pública', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8413', 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8414', 'Actividades reguladoras y facilitadoras de la actividad económica', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8415', 'Actividades de los otros órganos de control', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8421', 'Relaciones exteriores', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8422', 'Actividades de defensa', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8423', 'Orden público y actividades de seguridad', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8424', 'Administración de justicia', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8430', 'Actividades de planes de Seguridad Social de afiliación obligatoria', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA, PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA (DIVISIÓN 84)'),
('8511', 'Educación de la primera infancia', 'ENSEÑANZA (DIVISIÓN 85)'),
('8512', 'Educación preescolar', 'ENSEÑANZA (DIVISIÓN 85)'),
('8513', 'Educación básica primaria', 'ENSEÑANZA (DIVISIÓN 85)'),
('8521', 'Educación básica secundaria', 'ENSEÑANZA (DIVISIÓN 85)'),
('8522', 'Educación media académica', 'ENSEÑANZA (DIVISIÓN 85)'),
('8523', 'Educación media técnica y de formación laboral', 'ENSEÑANZA (DIVISIÓN 85)'),
('8530', 'Establecimientos que combinan diferentes niveles de educación', 'ENSEÑANZA (DIVISIÓN 85)'),
('8541', 'Educación técnica profesional', 'ENSEÑANZA (DIVISIÓN 85)'),
('8542', 'Educación tecnológica', 'ENSEÑANZA (DIVISIÓN 85)'),
('8543', 'Educación de instituciones universitarias o de escuelas tecnológicas', 'ENSEÑANZA (DIVISIÓN 85)'),
('8544', 'Educación de universidades', 'ENSEÑANZA (DIVISIÓN 85)'),
('8551', 'Formación académica no formal', 'ENSEÑANZA (DIVISIÓN 85)'),
('8552', 'Enseñanza deportiva y recreativa', 'ENSEÑANZA (DIVISIÓN 85)'),
('8553', 'Enseñanza cultural', 'ENSEÑANZA (DIVISIÓN 85)'),
('8559', 'Otros tipos de educación n.c.p.', 'ENSEÑANZA (DIVISIÓN 85)'),
('8560', 'Actividades de apoyo a la educación', 'ENSEÑANZA (DIVISIÓN 85)'),
('8610', 'Actividades de hospitales y clínicas, con internación', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8621', 'Actividades de la práctica médica, sin internación', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8622', 'Actividades de la práctica odontológica', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8691', 'Actividades de apoyo diagnóstico', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8692', 'Actividades de apoyo terapéutico', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8699', 'Otras actividades de atención de la salud humana', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8710', 'Actividades de atención residencial medicalizada de tipo general', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8720', 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8730', 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8790', 'Otras actividades de atención en instituciones con alojamiento', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8810', 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('8890', 'Otras actividades de asistencia social sin alojamiento', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL (DIVISIÓN 86, 87 Y 88)'),
('9001', 'Creación literaria', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9002', 'Creación musical', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9003', 'Creación teatral', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9004', 'Creación audiovisual', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9005', 'Artes plásticas y visuales', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9006', 'Actividades teatrales', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9007', 'Actividades de espectáculos musicales en vivo', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9009', 'Otras actividades de espectáculos en vivo', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9101', 'Actividades de bibliotecas y archivos', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9102', 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9103', 'Actividades de jardines botánicos, zoológicos y reservas naturales', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9200', 'Actividades de juegos de azar y apuestas', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9311', 'Gestión de instalaciones deportivas', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9312', 'Actividades de clubes deportivos', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9319', 'Otras actividades deportivas', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9321', 'Actividades de parques de atracciones y parques temáticos', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9329', 'Otras actividades recreativas y de esparcimiento n.c.p.', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS (DIVISIÓN 90, 91, 92 Y 93)'),
('9411', 'Actividades de asociaciones empresariales y de empleadores', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9412', 'Actividades de asociaciones profesionales', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9420', 'Actividades de sindicatos de empleados', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9491', 'Actividades de asociaciones religiosas', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9492', 'Actividades de asociaciones políticas', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9499', 'Actividades de otras asociaciones n.c.p.', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9511', 'Mantenimiento y reparación de computadores y de equipo periférico', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9512', 'Mantenimiento y reparación de equipos de comunicación', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9521', 'Mantenimiento y reparación de aparatos electrónicos de consumo', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9522', 'Mantenimiento y reparación de aparatos domésticos y equipos domésticos y de jardinería', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9523', 'Reparación de calzado y artículos de cuero', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9524', 'Reparación de muebles y accesorios para el hogar', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9529', 'Mantenimiento y reparación de otros efectos personales y enseres domésticos', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9601', 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9602', 'Peluquería y otros tratamientos de belleza', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9603', 'Pompas fúnebres y actividades relacionadas', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9609', 'Otras actividades de servicios personales n.c.p.', 'OTRAS ACTIVIDADES DE SERVICIOS (DIVISIÓN 94, 95 Y 96)'),
('9700', 'Actividades de los hogares individuales como empleadores de personal doméstico', 'ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES, ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO (DIVISIÓN 97 Y 98)'),
('9810', 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio', 'ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES, ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO (DIVISIÓN 97 Y 98)'),
('9820', 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio', 'ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES, ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO (DIVISIÓN 97 Y 98)'),
('9900', 'Actividades de organizaciones y entidades extraterritoriales', 'ACTIVIDADES DE ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES (DIVISIÓN 99)');