UPDATE CAT_PERMISSION SET `DESCRIPTION` = "Activar/Inactivar usuarios" WHERE CODE = "ENABLE_OR_DISABLE_BOCC_USER";
UPDATE CAT_PERMISSION SET `APPLIES_TO_USER_TYPE` = "ENTERPRISE_USER" WHERE CODE = "APPROVE_FINANCING_PLAN";
UPDATE CAT_PERMISSION SET `APPLIES_TO_USER_TYPE` = "ENTERPRISE_USER" WHERE CODE = "SET_TERM_NO_COST";

INSERT INTO CAT_PERMISSION (CODE, DESCRIPTION, APPLIES_TO_USER_TYPE, CREATION_DATE, ENABLED, `ORDER`, SEGMENT_CODE) VALUES 
('ACTIVATE_FINANCING_PLAN', 'Activar plan de financiación', 'LIBERA_USER', CURRENT_TIMESTAMP, 1, 12, 'FINANCIAL_CONDITIONS'),
('DELETE_FINANCING_PLAN', 'Eliminar plan de financiación', 'LIBERA_USER', CURRENT_TIMESTAMP, 1, 13, 'FINANCIAL_CONDITIONS'),
('CONSULT_OBLIGATION', 'Consultar obligación', 'LIBERA_USER', CURRENT_TIMESTAMP, 1, 5, 'QUERIES');