ALTER TABLE CAT_CURRENCY AUTO_INCREMENT = 1;

INSERT INTO CAT_CURRENCY(CODE,DESCRIPTION) VALUES
('AFN','Afgani afgano'),
('ALL','Lek'),
('EUR','Euro'),
('DZD','Dinar argelino'),
('AOA','Kwanza angoleño'),
('XCD','Dólar del Caribe Oriental'),
('SAR','Riyal saudí'),
('ARS','Peso argentino'),
('AMD','Dram armenio'),
('AWG','Florín arubeño'),
('AUD','Dólar australiano'),
('AZN','Manat azerbaiyano'),
('BSD','Dólar bahameño'),
('BDT','Taka'),
('BBD','Dólar de Barbados'),
('BHD','Dinar bareiní'),
('BZD','Dólar beliceño'),
('XOF','Franco CFA de África Occidental'),
('BMD','Dólar bermudeño'),
('BYR','Rublo bielorruso'),
('MMK','Kyat birmano'),
('BOB','Boliviano'),
('BOV','Mvdol'),
('USD','Dólar estadounidense'),
('BAM','Marco bosnioherzegovino'),
('BWP','Pula'),
('BRL','Real brasileño'),
('BND','Dólar de Brunei'),
('BGN','Lev'),
('BIF','Franco burundés'),
('BTN','Ngultrum butanés'),
('CVE','Escudo caboverdiano'),
('KHR','Riel camboyano'),
('XAF','Franco CFA de África Central'),
('CAD','Dólar canadiense'),
('CLF','Unidad de Fomento'),
('CLP','Peso chileno'),
('CNY','Renminbi'),
('COP','Peso colombiano'),
('COU','Unidad de valor real'),
('KMF','Franco comorense'),
('CDF','Franco congoleño'),
('CRC','Colón costarricense'),
('HRK','Kuna'),
('CUC','Peso convertible'),
('CUP','Peso cubano'),
('ANG','Florín antillano neerlandés'),
('DKK','Corona danesa'),
('EGP','Libra egipcia'),
('SVC','Colón'),
('AED','Dirham DE EAU'),
('ERN','Nakfa'),
('USN','Dólar estadounidense (Next day)'),
('ETB','Birr etíope'),
('FJD','Dólar fiyiano'),
('PHP','Peso filipino'),
('XDR','SDR (Derecho Especial de Retiro)'),
('GMD','Dalasi'),
('GEL','Lari'),
('GHS','Cedi'),
('GIP','Libra gibraltareña'),
('GTQ','Quetzal'),
('GBP','Libra esterlina'),
('GNF','Franco guineano'),
('GYD','Dólar guyanés'),
('HTG','Gourde'),
('HNL','Lempira'),
('HKD','Dólar de Hong Kong'),
('HUF','Forinto húngaro'),
('INR','Rupia india'),
('IDR','Rupia indonesia'),
('IQD','Dinar iraquí'),
('NOK','Corona noruega'),
('ISK','Corona islandesa'),
('KYD','Dólar de las Islas Cayman'),
('NZD','Dólar de la Islas Cook'),
('FKP','Libra malvinense'),
('SBD','Dólar de Islas Salomón'),
('ILS','Nuevo séquel'),
('JMD','Dólar jamaiquino'),
('JPY','Yen'),
('JOD','Dinar jordano'),
('KZT','Tenge kazajo'),
('KES','Chelín keniano'),
('KGS','Som'),
('KWD','Dinar kuwaití'),
('LSL','Loti'),
('ZAR','Rand'),
('LRD','Dólar liberiano'),
('LYD','Dinar libio'),
('CHF','Franco suizo'),
('LBP','Libra libanesa'),
('MOP','Pataca'),
('MKD','Dinar'),
('MGA','Ariary malgache'),
('MYR','Ringgit malayo'),
('MWK','Kwacha malauí'),
('MVR','Rupia de maldivas'),
('MAD','Dírham marroquí'),
('MUR','Rupia de Mauricio'),
('MRO','Uguiya'),
('MNT','Tugrik'),
('MZN','Metical mozambiqueño'),
('MXN','Peso mexicano'),
('MXV','Unidad de Inversion Mexicana(UDI)'),
('NAD','Dólar de Namibia'),
('NPR','Rupia nepalí'),
('NIO','Córdoba oro'),
('NGN','Naira'),
('XPF','Franco CFP'),
('OMR','Rial omaní'),
('XUA','BAD UNIDAD DE CUENTAS'),
('PKR','Rupia pakistaní'),
('PAB','Balboa'),
('PGK','Kina'),
('PYG','Guaraní'),
('PEN','Nuevo Sol'),
('PLN','Zloty'),
('QAR','Riyal catarí'),
('LAK','Kip laosiano'),
('VEF','Bolívar'),
('CZK','Czech Koruna'),
('KRW','Won'),
('MDL','Leu Moldavo'),
('KPW','Won norcoreano'),
('DOP','Peso dominicano'),
('IRR','Rial iraní'),
('TZS','Chelín tanzano'),
('SYP','Libra siria'),
('RWF','Franco ruandés'),
('RON','Leu rumano'),
('RUB','Rublo ruso'),
('WST','Tala'),
('STD','Dobra'),
('SHP','Libra de Santa Helena'),
('RSD','Dinar serbio'),
('SCR','Rupia de Seychelles'),
('SLL','Leone'),
('SGD','Dólar de Singapur'),
('XSU','Sucre'),
('SOS','Chelín somalí'),
('LKR','Rupia de Sri Lanka'),
('SZL','Lilangeni'),
('SDG','Libra sudanesa'),
('SSP','Libra sursudanesa'),
('SEK','Corona sueca'),
('CHE','WIR Euro'),
('CHW','Franco WIR'),
('SRD','Dólar de Surinam'),
('THB','Baht'),
('TWD','Nuevo dólar de Taiwán'),
('TJS','Somoni'),
('TOP','Pa’anga'),
('TTD','Dólar de Trinidad y Tobago'),
('TMT','Manat turcomano'),
('TRY','Lira turca'),
('TND','Dinar tunecino'),
('UGX','Chelín ugandés'),
('UAH','Grivnia'),
('UYI','Peso uruguayo en unidades indexadas (URUIURUI)'),
('UYU','Peso uruguayo'),
('UZS','Som uzbeko'),
('VUV','Vatu'),
('VND','Dong'),
('YER','Rial yemení'),
('DJF','Franco yibutiano'),
('ZMW','Kwacha zambiano'),
('ZWL','Dólar zimbabuense')