-- removing the property of autoincremento
ALTER TABLE ENTERPRISE_INVOICE_NEGOTIATION_PROCESS MODIFY NEGOTIATION_PROCESS_ID BIGINT NOT NULL;
-- removing primary key
ALTER TABLE ENTERPRISE_INVOICE_NEGOTIATION_PROCESS DROP PRIMARY KEY;
-- adding incremental auto primary key
ALTER TABLE ENTERPRISE_INVOICE_NEGOTIATION_PROCESS MODIFY NEGOTIATION_PROCESS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT