ALTER TABLE CAT_SECTOR AUTO_INCREMENT = 1;

INSERT INTO CAT_SECTOR(NAME) VALUES
('Aerolínea'),
('Agencia de publicidad'),
('Agricultura'),
('Asesoria'),
('Banca comercial'),
('Bebidas y alimentos'),
('Conglomerados'),
('Construcción'),
('Construcción Naval'),
('Consultoría'),
('Cosméticos'),
('Defensa'),
('Editoriales'),
('Emisoras de radio'),
('Energía y petroquímica'),
('Equipos industriales y maquinaria'),
('Fabricantes de piezas de Automóviles'),
('Hoteles'),
('Joyería'),
('Logistíca y mensajería'),
('Materiales de construcción'),
('Medios de comunicación y entretenimiento'),
('Minería'),
('Odontología'),
('Papel y plástico'),
('Prendas de vestir, calzado y textiles'),
('Restaurantes'),
('Salud y farmacéuticos'),
('Seguros, inversiones y pensiones'),
('Servicios médicos'),
('Servicios públicos e infraestructura'),
('Telecomunicaciones'),
('Ventas al pormenor'),
('Otras')