INSERT INTO REL_ROLE_PERMISSION (ROLE, PERMISSION, CREATION_DATE) VALUES 
('BOOC_VIEWER', 'READ_AVAILABILITIES',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_ENTERPRISE_DETAIL',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_ENTERPRISE_DOCUMENTATION',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_ENTERPRISE_LINKINGS_LIST',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_ENTERPRISE_LIST',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_FILED_OPERATIONS',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_FINANCING_PLAN_LIST',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_INVOICES_LIST',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_INVOICES_PENDING_AUTHORIZATION',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_NEGOTIATED_INVOICES',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_OPERATIONS_STATUS',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_PROVIDERS_LINKINGS',CURRENT_TIMESTAMP()),
('BOOC_VIEWER', 'READ_ROLE_LIST',CURRENT_TIMESTAMP());
