export enum DiscountNegotiationsLogBookStatusEnum {
    PROVIDER_PENDING_RESPONSE = "PROVIDER_PENDING_RESPONSE",
    PAYER_PENDING_RESPONSE = "PAYER_PENDING_RESPONSE",
    EXPIRED = "EXPIRED",
    CANCELLED = "CANCELLED",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    CREATED = "CREATED",
    COUNTEROFFERED = "COUNTEROFFERED"
}