export enum EnterpriseInvoiceFundingProcessStatus {
    PENDING_LENDER_PAYMENT_CONFIRMATION = 'PENDING_LENDER_PAYMENT_CONFIRMATION',
    PENDING_PROVIDER_PAYMENT_CONFIRMATION = 'PENDING_PROVIDER_PAYMENT_CONFIRMATION',
    REJECTED = 'REJECTED',
    PROVIDER_PAYMENT_CONFIRMATION = 'PROVIDER_PAYMENT_CONFIRMATION',
    LENDER_PAYMENT_CONFIRMATION = 'LENDER_PAYMENT_CONFIRMATION',
    EXPIRED = 'EXPIRED'
}

export enum EnterpriseInvoiceFundingRoleEnum{
    PAYER = 'PAYER',
    PROVIDER = 'PROVIDER',
    LENDER = 'LENDER'
}