export enum EnterpriseLinkStatus {
    PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
    PENDING_AUTHORIZATION = 'PENDING_AUTHORIZATION',
    PENDING_VALIDATION = 'PENDING_VALIDATION',
    PENDING_LINK_CREATION = 'PENDING_LINK_CREATION',
    ENABLED = 'ENABLED',
    DISABLED = 'DISABLED',
    REJECTED = 'REJECTED'
}