

export enum EnterpriseRecordTypeEventEnum {
  SING_UP = 'SING_UP',
  CREATION = 'CREATION',
  RESEND_INVITE = 'RESEND_INVITE',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  DOCUMENT_REQUESTED = 'DOCUMENT_REQUESTED',
  ENTERPRISE_REJECTED = 'ENTERPRISE_REJECTED',
  ENTERPRISE_APPROVED = 'ENTERPRISE_APPROVED',
  MODULE_APPROVED = 'MODULE_APPROVED',
  MODULE_REJECTED = 'MODULE_REJECTED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  MODULE_REQUESTED = 'MODULE_REQUESTED'
}

