export enum EnterpriseQuotaRequesRateTypeEnum {
    DUE_MONTH_RATE = 'DUE_MONTH_RATE',
    FIXED_RATE = 'FIXED_RATE',
    ANNUAL_RATE = 'ANNUAL_RATE',
    ADVANCE_MONTH_RATE = 'ADVANCE_MONTH_RATE',
    PREFERENTIAL_RATE = 'PREFERENTIAL_RATE',
    VARIABLE_RATE = 'VARIABLE_RATE'
}