export enum EnterpriseFundingLinkStatusEnum {
    PENDING_LENDER_APPROVAL = 'PENDING_LENDER_APPROVAL',
    PENDING_PAYER_APPROVAL = 'PENDING_PAYER_APPROVAL', 
    ENABLED = 'ENABLED',
    REJECTED = 'REJECTED'
}