export enum EntitytoRecordEnum {

  ENTERPRISE_NAME = 'ENTERPRISE_NAME',
  OWNER_NAME = 'OWNER_NAME',
  ENTERPRISE_TYPE = 'ENTERPRISE_TYPE',
  ENTERPRISE_SECTOR = 'ENTERPRISE_SECTOR',
  OWNER_FIRST_SURNAME = 'OWNER_FIRST_SURNAME',
  OWNER_SECOND_SURNAME = 'OWNER_SECOND_SURNAME',
  LADA = 'LADA',
  PHONE = 'PHONE',
  PAYER = 'PAYER',
  PROVIDER = 'PROVIDER',
  LENDER = 'LENDER',
  CHAMBER_OF_COMMERCE_CERTIFICATE = 'CHAMBER_OF_COMMERCE_CERTIFICATE',
  ENROLLMENT_FORM = 'ENROLLMENT_FORM',
  FUNDING_AGREEMENT = 'FUNDING_AGREEMENT',
  LEGAL_REPRESENTATIVE_ID = 'LEGAL_REPRESENTATIVE_ID',
  PAYER_AGREEMENT = 'PAYER_AGREEMENT',
  PROVIDER_AGREEMENT = 'PROVIDER_AGREEMENT',
  RUT = 'RUT',
  SHAREHOLDING_STRUCTURE = 'SHAREHOLDING_STRUCTURE',

}