export enum EFinancingPlanType {
  EXPONENTIAL = 'EXPONENTIAL',
  COMMISSION = 'COMMISSION',
  FUNDED = 'FUNDED',
}

export enum EFinancingPlanPaymentMethod {
  INTEREST_PER_MONTH_AND_CAPITAL_AT_MATURITY = 'INTEREST_PER_MONTH_AND_CAPITAL_AT_MATURITY',
  INTEREST_AND_CAPITAL_AT_MATURITY = 'INTEREST_AND_CAPITAL_AT_MATURITY',
  INTEREST_AND_CAPITAL_PER_MONT = 'INTEREST_AND_CAPITAL_PER_MONT'
}

export enum EFinancingPlanClientPermission {
  TERM = 'TERM',
  RATE = 'RATE',
  DAYS = 'DAYS',
  DISCOUNT = 'DISCOUNT',
  DAYS_FINANCED_TERM = 'DAYS_FINANCED_TERM',
  RATE_FINANCED_TERM = 'RATE_FINANCED_TERM'
}

export enum EinancingPlanStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
  CURRENT = 'CURRENT',
  ABOUT_TO_EXPIRE = 'ABOUT_TO_EXPIRE',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
  REJECTED_BY_ENTERPRISE = 'REJECTED_BY_ENTERPRISE',
  REJECTED_BY_LIBERA = 'REJECTED_BY_LIBERA',
  TIMED_OUT = 'TIMED_OUT'
}

export enum EFinancingObservations {
  ECONOMIC_GROUP = 'ECONOMIC_GROUP',
  SPECIAL_RATE = 'SPECIAL_RATE',
  AGREEMENT = 'AGREEMENT'
}

export enum EPaymentMethod {
  INTEREST_PER_MONTH_AND_CAPITAL_AT_MATURITY = 'INTEREST_PER_MONTH_AND_CAPITAL_AT_MATURITY',
  INTEREST_AND_CAPITAL_AT_MATURITY = 'INTEREST_AND_CAPITAL_AT_MATURITY',
  INTEREST_AND_CAPITAL_PER_MONTH = 'INTEREST_AND_CAPITAL_PER_MONTH'
}

export enum FPlanStatus {
  CURRENT = 'CURRENT',
  ABOUT_TO_EXPIRE = 'ABOUT_TO_EXPIRE',
  EXPIRED = 'EXPIRED'
}