export enum FinancingPlanStatusActionsEnum {
    APPROVE = 'APPROVE',
    DECLINE = 'DECLINE'
}

export enum FinancingPlanStatusEnum {
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
    CURRENT = 'CURRENT',
    REJECTED_BY_LIBERA = 'REJECTED_BY_LIBERA',
    REJECTED_BY_ENTERPRISE = 'REJECTED_BY_ENTERPRISE',
    ABOUT_TO_EXPIRE = 'ABOUT_TO_EXPIRE',
    EXPIRED = 'EXPIRED',
    TIMED_OUT = 'TIMED_OUT'
}